### ISSUE TITLE
首次登录请求没有携带UserAgent

### ISSUE THREAD

**Issue by bbbboom** [kraity/typecho-xmlrpc#2]
首次登录请求没有在请求头中携带UserAgent，导致ua为空被我的nginx配置拦截。
能否在第一次请求里带上ua，防止被当成恶意请求被拦截？

**Comment by kraity** [comment]
从已发布的版本v1.6开始，每一次请求的请求头都携带了UserAgent了的。

**Comment by bbbboom** [comment]
的确是最新版（1.6），强行停止清空数据后可以了，再次测试如果typecho不是在根目录的话。域名填写“yuming.com/blog”后，可以登录，但会直接闪退（android 10）。
如果xmlrpc是原版，客户端是老版本（可以使用原版xmlrpc）直接升级的，点个人信息会闪退，其他页面没有具体测试。

**Comment by kraity** [comment]
好的，谢谢反馈。那个你提交的pr，新增路由，很不错。但是typecho官方的xmlrpc中，存在用户弱权限问题，所以我去掉了官方的，就导致了不兼容。
