### ISSUE TITLE
app一直很赞！但是强制升级真是麻烦透了。我只想安心写个博客，不想天天折腾网站

### ISSUE THREAD

**Issue by dylanbai8** [kraity/typecho-xmlrpc#4]
app一直很赞！但是强制升级真是麻烦透了。
我只想安心写个博客，不想天天折腾网站。

希望作者能理解。

**Comment by kraity** [comment]
你好，谢谢支持南博。
的确每次更新APP就要替换xmlrpc文件，这个操作挺让人嫌麻烦的。
但是目前的XmlRpc.php还没有形成稳定的结构，在南博前期，还是需要替换，大概在v3.0时候开始，就不再强制替换了。

目前关于XmlRpc.php的替换，我们已写了一个插件。这样，可以在南博app上进行自动替换，免去了麻烦的操作。
 https://github.com/kraity/typecho-Aidnabo （南博助手 - 配套插件 - XmlRpc更新、接口安全）
https://docs.nabo.krait.cn/#/course-aidnabo （南博助手 - 使用步骤）

**Comment by dylanbai8** [comment]
感谢作者一直以来的辛勤付出！
南博是我见过最好的博客客户端，其实也是我能找到的唯一的博客客户端。

但是，
每当心血来潮，拿出手机想写点东西，却发现APP被“强制禁用了”。

**强制禁用旧版，真是个垃圾操作。**

一次还行，次次这样真是没劲，
我不想总折腾网站。

我只想随时随地掏出手机，记录一点东西。
